#apiVersion: v1
#kind: Secret
#metadata:
#  name: taiga-mappable-secrets
#  namespace: pbs-taiga
#type: Opaque
#data:
#  EVENTS_RABBITMQ_ERLANG_COOKIE:
#  EVENTS_RABBITMQ_PASS:
#  ASNYC_RABBITMQ_ERLANG_COOKIE:
#  ASYNC_RABBITMQ_PASS:
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: taiga-secrets
#  namespace: pbs-taiga
#type: Opaque
#data:
#  POSTGRES_PASSWORD:
#  TAIGA_SECRET_KEY:
#  EVENTS_PUSH_BACKEND_URL: "amqp://${EVENTS_RABBITMQ_USER}:${EVENTS_RABBITMQ_PASS}@${TAIGA_EVENTS_RABBITMQ_HOST:-taiga-events-rabbitmq}:5672/${EVENTS_RABBITMQ_VHOST}"
#  CELERY_BROKER_URL: "amqp://${ASYNC_RABBITMQ_USER}:${ASYNC_RABBITMQ_PASS}@${TAIGA_ASYNC_RABBITMQ_HOST:-taiga-async-rabbitmq}:5672/${ASYNC_RABBITMQ_VHOST}"
#  EMAIL_HOST_PASSWORD:
#  OIDC_RP_CLIENT_SECRET:
